### ISSUE TITLE
[Wishlist] Improved hotbar

### ISSUE THREAD

**Issue by Matakor** [jrbudda/minecrift#113]
I've only played for about 30 minutes, but the thing that jumped out at me immediately was how unwieldy the hotbar is. I have an idea to help with that: a wheel around your hand. 

Now, per the idea, selecting on the wheel isn't done by using the thumb-pad, but instead holding the left-hand grip button (right if reverse). Once the hold button is clicked, it pulls up the hotbar wheel. The wheel has the normal 9 boxes, and the boxes remain stationary at the point it's pulled up, allowing the player to move the controller to a box, which selects the box, then letting go to select and use the item in that box. 

I figure this would work FAR better as a hot-bar than the current rendition, allowing us to have set boxes with items that become muscle memory to grab. E.G, I have the sword in slot one. An enemy appears in front of me, I grip the controller, move the controller straight up, and release. I now hold the sword and can attack. If done right, I've grabbed it about as fast as it takes to hit a hotkey.

What do you think?

**Comment by Matakor** [comment]
On second thought, having the hot-wheel on the hand you're actually using/placing items would be FAR better. Right hand grip for standard, left for reverse.

**Comment by fazo96** [comment]
That would be way better than the current system, however I have other ideas:
- you point with your main hand to the hotbar in the offhand and pull the trigger to select. some kind of ray shows you which cell you're pointing
- you point with your main hand to the HUD on the offhand and pull the trigger, the inventory opens (but stays anchored to your offhand) and from there you can do everything by pointing and dragging and you have a third button used to select stuff in the hotbar to equip it in main hand

And another suggestion related to the HUD:
- the HUD is on the side of your hand instead of on top (rotated 90 degrees) and only shows up when it's orthogonal to your face and your controller is sideways, like the game Cosmic Trip does it

**Comment by possi** [comment]
I really like the initial idea of the gesture-wheel. Switching slots without looking at any hand would be cool.

**Comment by Valadon** [comment]
This is something that I didn't know I needed until you mentioned it. Now I don't know how I could possibly live without a "hot-wheel". I really like the idea, but I have no idea if it is possible to program easily.

**Comment by Matakor** [comment]
@Valadon It probably wouldn't be that difficult. Use the same method that is used for 'placing' the in-game pause menu, but give it a gesture based selection rather than 'mouse point' selection. Of course, he'd have to make the menu himself, as there's nothing in minecraft that comes close.

Except maybe Thaumcraft's wand selection.

**Comment by Aesop112** [comment]
The steam controller was like that. You could set it and Simply touching the touchpad would bring up a totally customizable wheel with labels and icons. Or you could spot grids and set the size and location of the grid.

**Comment by IVIrEos** [comment]
Is it possible to change what the hotbar actually looks like?
Can you re-arrange the graphic entity to mimic a 3x3 grid?
If so, then that solves the issue of needing a visual reinforcement when you give the touchpad itself a 9 digit emulation, Given the inherent flaws of the user interfacing within such small areas on the pad, and not knowing where their thumb actually is.  This would be almost perfect.. given the difficulty of trying to add steams UI pop ups into the game.

Because then you could just bind 1-9 to each and then you'd have the hotbar to give you feedback.

But then you have to find a place for jump and ... whatever.

**Comment by jrbudda** [comment]
the possibilities are limitless!

**Comment by Matakor** [comment]
@fazo96 Actually, the reason I suggested it the way I did is so that you don't necessarily have to look to see what you're grabbing. Most people tend to push a particular hotbar 'set', leaving certain tools in certain boxes. With it being a 'hotwheel', all you have to do is move your hand to the area that you already know your tool is set to. This would be FAR faster than having a 'beam' or 'ray' pointing to an object on another hand to choose your tool. You have to actively look at it at all times, rather than a quick familiarization the wheel method gives.

On the other hand, having a beam/ray method for accessing your FULL inventory this way... that could work. Example: wheel attached to my right hand (dominant hand), lets me quick access to the hotbar, so I can quickly switch between tools and such. I need to change out one of my hotbar items, so I turn over my left (non-dominant hand) hand so the controller faces me, and viola, there's the full inventory page, accessible by beam/ray. To the side of the inventory is a copy of the wheel, letting you place you hotbar items without having to move an excessive amount. 

For 1.7, this would work great. 1.10 has two hands though, so this could probably go more like so: hotwheel to both hands, and each hand can pick it's tool/etc. Inventory access is available to both hands by flipping the controller to face you, and the hotwheel is displayed on the inner arm, closer to the elbow on each side.

Of course, the flip-method should only allow access to the basic inventory, to keep from cluttering, so no crafting or armor slots visible. That way it can be a bit larger without taking up a portion of the screen.

@jrbudda man, sometimes I wish I was capable of actually programming anything. I'd help out a lot more by actually doing stuff rather than suggesting. xP

**Comment by fazo96** [comment]
> For 1.7, this would work great. 1.10 has two hands though, so this could probably go more like so: hotwheel to both hands, and each hand can pick it's tool/etc. Inventory access is available to both hands by flipping the controller to face you, and the hotwheel is displayed on the inner arm, closer to the elbow on each side.

This is a great idea! Way better than mine. You're right about it being more usable. I think your onto something @Matakor ! :smile:

**Comment by jrbudda** [comment]
I do like the idea of positional inventory opening, it frees up a button, 2 issues come to mind for you to ponder:

the screen reallllly needs to be fixed in space once opened and not move with the hand. So 
1)you really need to detect when the player wants the inventory to open, and not have any false positive from just moving around.
2) How do you close it?

**Comment by Matakor** [comment]
Hmm... Yeah, that method could cause false positives...

What about having the inventory open when you position the disc to face you? And for further control, have the stick pointing to the ground. Like so: ![Image of position](http://i.imgur.com/L32PsN2.jpg)

And to close it, have it close any time it moves away from that position. Is positional closing possible? rather than using a button?

**Comment by CodeKartonka** [comment]
http://www.youtube.com/watch?v=RyMqzetYudg&t=7m20s
Best ingame invertory menü :-) i seen in steam

Maybe 250 degrees round one?

One button for Blocks
http://www.youtube.com/watch?v=RyMqzetYudg&t=7m20s

Other button for weapons like in this demo :-) 
https://www.youtube.com/watch?v=RyMqzetYudg&t=16m05s

(Ignore Teleporting) :dash:

**Comment by jrbudda** [comment]
So for anyone following this discussion I've started on a slightly improved hotbar for the next release. Right now it defaults to being invisible unless you look at the inside of your left arm. You can select items by touching them.

I don't think this will be the final release version because the positioning isnt that great and I think some smaller version of the hud needs to be displayed all the time. So I'm looking for some feedback.

For this version:
A) I'm not going to change how the hotbar is actually rendered, no circles or grid or whatever, not for 1.7.10 anyway.
B) Need the best place for the bar to be all the time for looking at your health/chat/etc
C) Whats the best orientation to pop up the touch menu? pointing the controller 'up' has been suggested instead of the side like it is now.

I welcome all feedback.

[vivecraft-1.7.10-Vivecraft-jrbudda27-installer.exe.zip](https://github.com/jrbudda/minecrift/files/354939/vivecraft-1.7.10-Vivecraft-jrbudda27-installer.exe.zip)

**Comment by jrbudda** [comment]
some more tweaks to this were made in 27 release. You can now touch the hotbar in 'hand' or 'wrist' mode

**Comment by IVIrEos** [comment]
The only suggestion I can make is to move the hotbar to where the watch would be. but not really, it only needs to move about 90 degrees.  Where it sits now, makes me have to turn my wrist as if to look at the bottom of it instead of the top. making it a bit awkard for me with the way the hotbar pivots out.  I was also thinking that instead of having it pivot out, leave it flat on the wrist but scale it up slightly to signify that it has become active.

**Comment by jrbudda** [comment]
i found that having to turn your wrist any further was really awkward, and if it was on the 'top' it would pop up too much... I'll think about your suggestions tho... I think most people are gonna stick with the normal hand mode now since I added touch to that.

**Comment by IVIrEos** [comment]
Actually, I just came back to rescind that suggestion.  I've gotten quite used to how this setup is working out.  And it's pretty efficient as is once you get over having a vertical hotbar instead of a horizontal one.

nevermind...

I was trying to bring my wrist up to my face instead of just holding straight out and looking down at it.  Makes all the difference.

**Comment by jrbudda** [comment]
Closing this I think it's pretty final for now.

**Comment by CodeKartonka** [comment]
Very nice work thank you !
Absolutely!

I Love you Touch HotBar it a Perfect solution for me if i use "Wrist" mode :-) just only need a slider to get offset from controller :D i hit them both sometimes 
(select 1 2 3 is too close to the other controller)
http://imgur.com/bdYHcus

Another point is:
It wold be wonderful if u can add a dual hotbar :-) (double Hotbar ?)
http://i.imgur.com/9fsq7e2.png
first row from the invertar would be perfect

sorry for bad english :-(
german here :-)

(i have no idea should i open a new issue? this one is closed no idea if u can read this one)
