### ISSUE TITLE
Items losing their block-breaking ability

### ISSUE THREAD

**Issue by jrbudda** [jrbudda/minecrift#121]
Sporadic reports of high-grade tools not working as intended.

**Comment by captroper** [comment]
Writing the issue as you requested. In both version 21 and 22 diamond tools, enchanted and otherwise , act as if they were lower grade tools (taking a while to break the block). Specifically, I have tried enchanted and un-enchanted diamond pickaxes on stone, un-enchanted diamond shovel on dirt, and enchanted diamond axe on acacia wood. All of this took place on a multiplayer vive server (vive.asparagus.farm), and switching back to Automat's version or stock 1.7.10 MC fixed the issue, while switching back to v22 reproduced it. I have also turned weapon collision on and off with no difference either way. 

Edit: I didn't change anything, but the issue appears to be gone now.

**Comment by jrbudda** [comment]
Maybe related to #149
