### ISSUE TITLE
[Forge only?] v21 and v22 makes me float above the ground, can't move and attack/break stuff

### ISSUE THREAD

**Issue by pmcthor777** [jrbudda/minecrift#127]
v21 and v22 causes my avatar to float a bit off the ground as soon as I load into the world, causing me not being able to move/teleport, and attack/break doesn't respond either. Reverting back to v20 resolves the issue.

**Comment by tylersb** [comment]
same issue & reverting to v20 is the only thing that solves it

**Comment by jrbudda** [comment]
Forge/vanilla? mods? single/multiplayer? What do you mean by 'avatar' ? Does changing any of the locomotion options affect what you're seeing?

**Comment by wildstyle007** [comment]
Am seeing this also; perhaps relates to new world scale (which is great by the way). Game was still playable for me, but was very noticable on first world spawn.

When trying to look outside doors / windows some strange glitching too..  cannot get close like normal.

**Comment by wildstyle007** [comment]
Made me feel like my vive was calibrated above floor level, but it wasn't.

**Comment by wildstyle007** [comment]
Some more info:
- I deleted the forge version and tested on vanilla, it worked great!!
- Then deleted the vanilla profile and reinstalled the forge version, the problem came back.

So, only affecting forge version for me at least.

**Comment by wildstyle007** [comment]
Important note: I was not experiencing the "can't move and attack/break stuff" part, just the floating and weird behavior near some objects, like doors / windows.

**Comment by wildstyle007** [comment]
Please note: If I turn Locomotion > "Allow crawling" OFF then the problem stops... for me at least.

**Comment by tylersb** [comment]
Forge installed, have not tried a clean install yet. Happens in both multiplayer and singleplayer for me. 

I've tried changing all the options I can think of, including optifine options and locomotion options but no matter what I'm still unable to interact with blocks/teleport/move.

The only button that works is viewing the game options & opening my inventory, but no other buttons seem to do anything including holding the side button to change locomotion style.

Also, it seems to lock my camera in 1 spot so that when I move my head up the world moves up with me & same thing for down, as opposed to getting closer or further from the ground like normal. I think that turning "Allow crawling" off seemed to stop this aspect, but it didn't fix any of the other issues.

I can still be interacted WITH by things like zombies, who just attack me until I die while I flail around in my house ineffectually.

**Comment by tylersb** [comment]
A little update for you with other things I've tried/found. I did a clean install of minecraft + forge + only the latest vivecraft installer (v22) and it seems like nothing has changed.

If I physically walk in in my room so that in the game I would fall off a ledge, then that still happens and I fall down in the game.

I found that the right controller's game menu button still works and will drop whatever I'm holding. So the left game menu button works and brings up the menu, the right game menu works and drops my items, and pressing up on the left controller pad still brings up the inventory and I can move items around my inventory as normal as well as use the right controller trigger and pad to see recipes in NEI.

None of the other buttons seem to work, however if I sit down at my computer I can still use my keyboard + mouse to do all the things that aren't working with the vive controllers like move forward, backward, and strafe (although still bound towards the direction the left controller is facing), destroy blocks & place blocks etc..

**Comment by jrbudda** [comment]
Have we confirmed that this only occurs with Forge installations?

**Comment by tylersb** [comment]
It seemed to for WildStyle but I personally haven't tried a non-forge installation so far

**Comment by jrbudda** [comment]
could you please? they can exist side by side

**Comment by tylersb** [comment]
Non-forge install seems to work without issues. I didn't try anything too extensive since I'm playing Overwatch right now but I was able to move with free move (holding left controller trigger), break grass and change the scale of my character. Didn't try allow crawling though because I was trying to get back to my game before I got kicked for inactivity... which ended up happening anyways.

**Comment by jrbudda** [comment]
Could you test with v23? I never was able to reproduce this one.

**Comment by tylersb** [comment]
Yeah I'll check it out and let you know

**Comment by tylersb** [comment]
Same issue seemed to be present, although I noticed that now any button press that didn't work previously seems to "left click repeatedly" until I press the right trigger again which gets it to stop

**Comment by jrbudda** [comment]
I still got nothin for this one. You said it works fine without Forge... Have you tried resetting the button mappings in your Forge install? are you using any mods at all?

**Comment by tylersb** [comment]
Lots of mods, I was just plugging everything in right now to test out v24 just in case but if it didn't fix things I was going to ask if there was anything else I could do/provide to help figure out the issue. I'll report back in a minute.

**Comment by tylersb** [comment]
Alright so V24 seemed to have the same problems, although the new thing from V23 seemed to have disappeared where "almost all buttons on vive controller cause character to repeatedly left click until the right trigger is pressed, in which case it stops happening (although right trigger doesn't initiate a left click, only stops the repeated clicking for some reason)"

That is, until I reset the button mappings for all mods/default keys back to default (I don't recall changing much anyways). Doing that brought back the "repeated left clicks" thing.

So, what can I attach that would help? I can give you the list of mods, I can attach the logs from the last game I just tried, and I used Shift+F3 to go down a few of the debug trees and took a couple screenshots that I can attach.

**Comment by jrbudda** [comment]
Well first thing is does it still do it with just Forge and no mods installed?

**Comment by tylersb** [comment]
Vivecraft Forge with 0 mods appears to work without issues, at least in a newly created world since I didn't have one like that previously

**Comment by pmcthor777** [comment]
I don't really have time to test in the near future, but here's my list of mods:
Baubles, CodeChickenLib, and ForgeMultipart resides in the "1.7.10" folder. Moved them out so you can see the complete list.

![image](https://cloud.githubusercontent.com/assets/20137399/16404343/ff1a88a4-3cb2-11e6-8707-583916aa8caa.png)

**Comment by jrbudda** [comment]
If vivecraft+forge with no mods works fine then what you have is a mod interaction bug. 

If you expect me to download and install all the mods on your list for the purpose of figuring out which one is causing the issue you will be waiting a very, very long time.

If you can pin down the culprit I will take a look at fixing it.

**Comment by pmcthor777** [comment]
Nah, I don't expect you to test the mods. Was thinking couple might jump out at you at a glance. Also, if tylersb posts his mods, we can see which ones we have in common and narrow it down.

**Comment by tylersb** [comment]
^figured the same. Will edit my post with my mods for now but have to head to sleep for work. I'll get around to narrowing it down eventually through process of elimination.

![image](https://cloud.githubusercontent.com/assets/17137364/16404788/f9ce81a8-3cb6-11e6-9a44-d29051d7fd4d.png)

and inside 1.7.10

![image](https://cloud.githubusercontent.com/assets/17137364/16404813/3fd8c690-3cb7-11e6-8a33-62e825f639e8.png)

**Comment by techgeek1** [comment]
I found the problematic mod! Its NotEnoughKeys. After removing it the controls work like they should. Tested on v23 and v24 and no issues after a few hours of gameplay.

**Comment by jrbudda** [comment]
sounds like case closed. Reopen if it happens again.
