### ISSUE TITLE
[Discussion] Walkabout locomotion

### ISSUE THREAD

**Issue by philpax** [jrbudda/minecrift#157]
As depicted here: https://www.youtube.com/watch?v=pW6nlLV88Zk

With the recent changes made to reference frames, this should now be possible.

**Comment by Techjar** [comment]
You seem to have accidentally truncated part of the video URL, so I cannot watch it as it "does not exist."

**Comment by philpax** [comment]
Err, my apologies. Fixed!

**Comment by IVIrEos** [comment]
I find that the new '180' option for 'World Rotation Increments' works pretty well in the meantime.

**Comment by jrbudda** [comment]
meantime schmeamtime. Bind Walkabout to whichever button you prefer.

[vivecraft-1.7.10-Vivecraft-jrbudda25r1-installer.exe.zip](https://github.com/jrbudda/minecrift/files/340581/vivecraft-1.7.10-Vivecraft-jrbudda25r1-installer.exe.zip)

**Comment by jrbudda** [comment]
put out a release of 25r1 which has walkabout but with the controller direction which is way better. Try that one.

**Comment by IVIrEos** [comment]
One thing I kind of noticed on the walkabout is that my chaperone wall disappears kind of quickly while turning.

**Comment by IVIrEos** [comment]
I noticed something with this new option.
You can actually use in combination w/ Forward movement to give you a 'Smooth Rotation' option.
This one change just obsoleted the World Rotation Increments (For me anyway)

Is it possible to add an option to reverse the direction that it rotates?
So that I can swipe my hand to the right to make it rotate right (instead of left)

Almost forgot to mention that when you do try to use walkabout + Artificial Forward movement, it introduces quite a bit of jitter.  But I'm not sure how much of that is due to this issue I'm having with the 1080 right now.

**Comment by jrbudda** [comment]
Yea don't do that. with the forward button. I'll need to make them mutually exclusive.

I feel like reversing the rotation would be horribly disorienting wouldn't it?

**Comment by IVIrEos** [comment]
Use it like you were playing it with a Rift, from a 180 seated experience.  Instead of standing 'walkabout'.  And you'll see what I mean about reversing it.  Maybe just have another ReverseAbout option in there.

Chaperon does not come on, when you press walkabout.   At times even when you are next to it.  The chaperone turns off too quickly, making you lose your reference of when to stop turning.  Is this something you can force to stay on while the button is held?

**Comment by jrbudda** [comment]
oh that turns it into a 'pan' button

**Comment by jrbudda** [comment]
I can try, it might require fading out the whole game

**Comment by IVIrEos** [comment]
by Mutually exclusive do you mean making it unable to 'pan' + 'Move Forward'?  Because with some tweaking I've done, I've gotten the game back to a playable state on this 1080.  And although it still has some jitter it's an almost 90% improvement over what I was experiencing earlier.  No idea what you'd be getting on a 970.  I'd almost prefer to keep it as is, jitter and all, if there is no other choice.

**Comment by jrbudda** [comment]
the jitter is not a performance issue it's the movement and rotation fighting each other to set the room origin. If you really think there's a need to do both at the same time i'll have to look into making them cooperate.

**Comment by jrbudda** [comment]
Ok now youve got a Rotate Free button along with a Walkabout button. They just rotate in opposite directions.

[vivecraft-1.7.10-Vivecraft-jrbudda25r1-installer.zip](https://github.com/jrbudda/minecrift/files/341882/vivecraft-1.7.10-Vivecraft-jrbudda25r1-installer.zip)

**Comment by IVIrEos** [comment]
Gave it a try... Awesome work.

And yes..  Flying around in creative mode while doing a seated 180 experience.  It's nice to have them co-operate.

**Comment by philpax** [comment]
Gave Walkabout a shot last night - it's very cool, but I'd prefer an option for using HMD direction (I know, I know, the locomotion settings window is already filled to the brim!)

The other major issue is that using walkabout is a fantastic way to get your cable tangled up beyond recognition, but I'll be giving it a shot with https://www.reddit.com/r/Vive/comments/4lwti7/turncountervr_a_rotation_counter_with_overlay/ to see if that improves things.

On the whole, though, it's a really cool proof of concept! Except it's much harder to run away from mobs now :stuck_out_tongue:

**Comment by jrbudda** [comment]
Oh I should mention in here that in v28 I fixed the jitteriness when rotating and walking at the same time.

**Comment by jrbudda** [comment]
v30/v3 will introduce a dimming of the world while using walkabout. Still no blur tho.
