### ISSUE TITLE
[Forge Mod] Portal gun doesn't fire

### ISSUE THREAD

**Issue by ghost** [jrbudda/minecrift#159]
http://minecraft.curseforge.com/projects/portal-gun

gun renders wierdly in hand (points at a wierd angle and floats)

gun is meant to fire 1 colour portal on left click and the other colour portal on right click...neither work

**Comment by Techjar** [comment]
First problem is related to issue #101. Second one I have no idea, we'll have to look into that later.

**Comment by Techjar** [comment]
Hmm, if I had to guess he's probably checking the mouse directly instead of using the usual item click stuff. I'll look into the code to be sure, but if that's the case then I'm not sure we can fix it, as the only way to get it working would be to put in awt.Robot calls for left and right click in the world too, which has it's own set of problems.

**Comment by Techjar** [comment]
So, turns out shooting portals is an entirely separate binding. At this point I'm not sure what we can do about this.

**Comment by Techjar** [comment]
Okay, in addition to being a separate binding, he's also checking the key/mouse button codes directly. We aren't going to mess with doing awt.Robot calls in world due to the issues it causes, so this can't be fixed. The GravityGun mod also has the same problem, except it checks the code directly of the vanilla attack/use bindings.
