### ISSUE TITLE
v26 -  Fast Render option

### ISSUE THREAD

**Issue by IVIrEos** [jrbudda/minecrift#164]
When I initially installed v26 I had this option already enabled.   Now everytime I go to enable it, it feels like it crashes the compistor.  My HMD just goes blank, but I can still see chaperone.  And I can hear the game running on the non-mirrored window.   But the game never comes back.  IF I change or disable the shader,  the game re-appears in the headset.  If I try to toggle fast-render is goes blank again.... but will come back if you change the shader again.

**Comment by Techjar** [comment]
Yeah, I looked into the code related to that option and I don't really understand how it's supposed to be any faster. A lot of the optifine options to seem be superfluous crap that only _maybe_ make a difference in some super weird edge cases, mainly on old shitty laptops and such. I'd just turn the option off and not worry about, as it's not going to provide any tangible performance boost. As for why it's having the effect of basically breaking the rendering, I have absolutely no idea.

**Comment by jrbudda** [comment]
The fix is to disable that option, found the issue, I thought I had disabled it.

**Comment by Techjar** [comment]
Okay, so while the previous statement still applies, I've found out why it's breaking everything when you toggle the option. The fast render option actually disables framebuffers (why!?), and we have modified it so that it shouldn't do this, but OptiFine was "doing goofy shit directly" when toggling the option. As jrbudda stated above, the option is entirely disabled now so this can't happen anymore. As I've said, it's useless anyways so there's no need for it.
