### ISSUE TITLE
ClassNotFoundException: net.minecraft.client.main.Main

### ISSUE THREAD

**Issue by arkad94** [jrbudda/minecrift#169]
[22:51:23] [main/INFO]: Loading tweak class name optifine.OptiFineTweaker
[22:51:23] [main/INFO]: Using primary tweak class name optifine.OptiFineTweaker
[22:51:23] [main/INFO]: Calling tweak class optifine.OptiFineTweaker
OptiFineTweaker: acceptOptions
OptiFineTweaker: injectIntoClassLoader skipped, OptiFine is loaded as a library
OptiFineTweaker: getLaunchArguments
OptiFineTweaker: getLaunchTarget
[22:51:23] [main/ERROR]: Unable to launch
java.lang.ClassNotFoundException: net.minecraft.client.main.Main
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_91]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_91]
    at java.lang.Class.forName0(Native Method) ~[?:1.8.0_91]
    at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_91]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:131) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
    ... 6 more
Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release

**Comment by jrbudda** [comment]
java.lang.ClassNotFoundException: net.minecraft.client.main.Main

it says the game is missing.

**Comment by kyle7575** [comment]
i have also had this exact problem since mod v25 only update 24 and down are working otherwise i get this error.

**Comment by Techjar** [comment]
Do you have Forge installed?

**Comment by kyle7575** [comment]
if you mean the base forge and not the update included then No i do not have it

**Comment by Techjar** [comment]
Can you post the full log file? Please be sure to strip out the Session ID at the top.

**Comment by kyle7575** [comment]
http://i.imgur.com/X9NQVXs.png

**Comment by Techjar** [comment]
I have no idea what's going on, try deleting .minecraft (backup saves and whatever else you want to keep) and starting from scratch.

**Comment by kyle7575** [comment]
I have done that 3 times now xD. im just hoping i can get future updates

**Comment by Techjar** [comment]
Oh... well I have no idea what's wrong. I can't fix something I can't reproduce. Maybe it'll work if you install Forge?

**Comment by kyle7575** [comment]
Extra info: on v24 it works as i said but if i load it with the shader pack included i get this same error
edit: forge installed but same thing

**Comment by jrbudda** [comment]
That's likely the changes I made to the json files, it's not finding the main minecraft jar. You actually need to look at the 'launcher log' tab in the launcher for errors. There may be extra steps needed.

**Comment by kyle7575** [comment]
Thank you very much I'm at work right now and I'll post it when I get home

**Comment by kyle7575** [comment]
i hope this helps @jrbudda 

http://i.imgur.com/EPFcBW9.png

im gunna be so happy if i can update past v24

**Comment by kyle7575** [comment]
FIXED!!! UPDATING TO V26 NOW TO TEST IF IT WORKS

updated java to x64 bit offline and problem was solved but v26 still gives me the same error
v25 is also giving the error but not v24 :<

ok so NOW v25 is exit code 0 withouth errors but not starting????

http://i.imgur.com/NV9TWGI.png 

@Techjar

**Comment by jrbudda** [comment]
dont use screenshots, get the whole logs with right click> copy text and put it on paste bin. Do both the launcher log tab and the game output tab

**Comment by kyle7575** [comment]
game output

http://pastebin.com/BXB3azFu

log tab

http://pastebin.com/rrurW4yW

v26

**Comment by kyle7575** [comment]
Game output 

http://pastebin.com/svvw5yzn

Logs

http://pastebin.com/B3Gahe2u

v25

**Comment by jrbudda** [comment]
Okay it seems like your Launcher's attempt to download the actual game is failing. Previous to version 25 my installer was setting that up but now the launcher does it.

Do you have some kind of fancy firewall running? Could something be blocking the the launcher's net access? If you can't figure it out, I'd like to see the same logs from a fresh install where you don't install vivecraft  and just load normal 1.7.10 because that download is working?

specifically this line 
[20:41:29 INFO]: Finished downloading C:\Users\win7\AppData\Roaming.minecraft\versions\vivecraft-1.7.10-Vivecraft-jrbudda26-shadersmod\vivecraft-1.7.10-Vivecraft-jrbudda26-shadersmod.jar for job 'Version & Libraries': Couldn't connect to server (responded with 403) 

should look like 
[09:32:40 INFO]: Finished downloading C:\Users\Administrator\AppData\Roaming.minecraft\versions\vivecraft-1.7.10-Vivecraft-jrbudda25r1\vivecraft-1.7.10-Vivecraft-jrbudda25r1.jar for job 'Version & Libraries': Downloaded successfully and hash matched

One other thing to try as an experiment is to run the launcher as administrator tho I don't think that's the problem.

If you can't get it to work what you can do as a workaround is go into .minecraft/versions/1.7.10/ and copy the 1.7.10.jar to the versions/vivecraft..../ folder and rename it to replace the jar that's already in there (which should only be 1kb in size)

**Comment by kyle7575** [comment]
On my way to work now but I'll do as you said when I get back home and to
answer your question I'm using basic windows firewall.  I have tried
running as administrator and my game does boot without vivecraft installed
on 1.7.10 fresh install.  I will get you those logs by 7 if I can remember

**Comment by kyle7575** [comment]
On the way home now I'll get you those logs and attach them to this comment if I can

No need for logs i found the problem... i feel stupid and embarrassed/guilty but when the FAQ said it worked with the demo i assumed an **offline** minecraft install would be fine but alas thats what you get for **not buying the game**... i didnt want to buy it cause i have bought the game over twice now but have lost the info twice also ... i bought the legit copy for the third time and presto it was fine... as for the mod. v24 and back work on all cracked/offline - clients/launchers but v25 and up are legit/paid copies only idk if this was intentional or not but now you know.

**Comment by jrbudda** [comment]
the workaround I posted about copying and renaming the jar should work for cracked versions.
