### ISSUE TITLE
Visual drop out issue. 

### ISSUE THREAD

**Issue by Chronixt** [jrbudda/minecrift#174]
Can't find this anywhere else. 
I'm running an Alienware 15 r2 with an graphics amplifier with and overclocked 1070 GTX. I'm using forge and a few mods. Now, lately I have been having some major dropping issues. It doesn't always happen straight away but usually it does. Every few seconds, for about half a second, the game fades back to the Vive home and back into the game. No stuttering at all in the game, even when I turn all the graphics down it still happens, tried deleting all mods and starting a new map and even reinstalled everything. I've also tried changing the xmn and xmx settings for more RAM. 
Any ideas?

**Comment by Chronixt** [comment]
By the way I absolutely freaking love this game and it's really gotten me back into minecraft and this issue has just made it too frustrating to play.

**Comment by Techjar** [comment]
Are you are experiencing is the game freezing for a few frames, causing SteamVR to go into "unresponsive" mode. There are some known issues like this in the game. Try installing Forge and putting fastcraft (http://forum.industrial-craft.net/index.php?page=Thread&threadID=10820) into the mods directory, see if that helps. Oh, and are you in a forest or anywhere with a lot of leaves?

**Comment by Chronixt** [comment]
Hey thanks so much for the reply. Looks like that has solved the issue!! Absolutely brilliant now I can actually get enjoy it!! 
Cheers!

**Comment by Simpsoid** [comment]
I was also having this issue and I tried the latest version of Fastcraft 1.23.

This didn't resolve anything for me an in fact Fastcraft reduced my fps to around 17fps. I get around 90fps in Vivecraft 27 with no shaders but it does drop out every 2 minutes or so for a few seconds. Only after playing for a couple of minutes though.

Any other suggestions?

**Comment by Techjar** [comment]
Try increasing your memory allocation, go to the launch arguments and change the -Xmx2G to like 3 or 4. Besides that I honestly have no idea.

**Comment by Simpsoid** [comment]
Yes my max memory is set to 5g and min to 2g. Fast craft just reduces my fps. Not sure why. I'm assuming some conflict actually causes Minecraft to do more work and therefore give less fps.

It's a shame because I still have the issue. Oced 2500k@4.5, 16gb ddr3@2133, oced 970. Game runs smooth by default (>90 fps in Vivecraft) but the dropped frames cause the fade to SteamVR frequently.

There's no reason why it should drop frames either because i can be standing in a perfectly loaded chunk doing nothing and it'll fade out.

**Comment by Simpsoid** [comment]
I still do get this issue. I've read that it can be caused by the garbage clean up of Java and setting too much memory is detrimental for this. Advice was a max mem of 4GB. I will try that and see whether that resolves it but last I played (with 5G and 8G of max memory set) I still had issues.
Edit: Not an issue with Vivecraft as I believe this was posted as a Vanilla bug, which seems likely.

**Comment by jrbudda** [comment]
Yea there's realllly not a lot I can do about this. You've got in-game stuff like chunk loading that's gonna hang up the game periodically and then JVM stuff like garbage collection that may do the same. It's all gonna depend on your CPU/Mobo/Ram/Disk speeds and what your PC is doing and the JVM settings and yea... can't really be helped from within the mod.

**Comment by Simpsoid** [comment]
Yeah I know and appreciate your effort, I think this is likely one of the bugs that will happen to some people but will not really have an ideal solution due to the massive range of configurations out there (PC specs, which java version / 32 or 64 bit, what other mods etc.). My PC is more than powerful enough (2500K@4.5, 16GB DDR3@2133, 970 OCed), no other mods but I am running a 256x texture pack. I'll keep reading and trying to resolve this and will update this with my findings, if any.

It's such an amazing game in VR. Thank you for all your effort and tireless hard work!
