### ISSUE TITLE
[Minor Issue] Binding the touchpad quater to a keybind and pressing while a gui is open also does the rightclick + Touchpad sending event when it should not..

### ISSUE THREAD

**Issue by GroxicTinch** [jrbudda/minecrift#183]
I have bound the touchpad UR to press the u key which I use with FTB to list all recipes the current item is used in, the problem is that pressing the quarter of the touchpad will rightclick and then press U which either ends in nothing being displayed because the item is now picked up or it picks up half the stack and when exiting the gui the items are dropped.

Would it be possible to only allow the "Use Item/Rightclick" bind to do the gui rightclicking to prevent issues like this when a button is needed to be pressed while inside a gui?

Also along with this issue the touchpad will also send its events while trying to type with the SteamVR keyboard out which is a problem for those that type using the touchpad as pressing the touchpad to insert a letter will also rightclick the object behind or try to use an object which exits out of the chat meaning we have to start again and instead use the pointer.

**Comment by Techjar** [comment]
Yeah this is because the UI right-click doesn't bother checking the touchpad position. We're checking the buttons directly in that code, maybe we should do some binding checks?

**Comment by IVIrEos** [comment]
I think this is somewhat related.  

I had re-bound sneak to Right trigger (Fullclick was changed to attack).

In creative, if you open up inventory and attempt to select an object while you were flying up high in the air, you would be unable to select anything because unlike the steam controller, it doesn't have a way to bypass the input from squeezing the trigger to get to Fullclick, and you end up moving downward.

Plus and I think you might be aware of this one already.   It looks like Fullclick happens long before the click actually happens.

Same goes true for binding any kind of action to the primary trigger, while in the game.  I've learned that if you are going to change bindings for the trigger.  Do it at the main menu.  Because in the process of cycling through the bindings, you're going to land on something that is going to force you to have to sit down and use the mouse and keyboard to exit out to the main menu anyway to fix it.
