### ISSUE TITLE
DoctorPC's Great List of Frustrations

### ISSUE THREAD

**Issue by DoctorPCfin** [jrbudda/minecrift#192]
https://www.dropbox.com/s/d2s1luiazvnq8m0/LetsMakeThisAnActualthing.png?dl=0

**Comment by jrbudda** [comment]
I was really hoping you'd include them as text.

**Comment by DoctorPCfin** [comment]
1. Tiny tools
2. Chopping wood  with a small reach
3. Creeper explosion radius > sword reach
4. Sleeping is strange as all hell
5. What is the formula for damage scaling?
6. No haptic eedback for swords
7. Haptic eedback doesn’t scale with swing
8. HUD occlusion doesn’t work*
   *or requires restart. I don’t know.

**Comment by jrbudda** [comment]
1. fixt in 1.10.2
2. bigger axe? how much bigger?
3. Can't mess with creeper because multiplayer, increase sword reach further?
4. How should it work? blank out the HMD?
5. Vivecraft makes no changes except to arrow damage and even that is likely singleplayer only.
6. Like what you hit something? I thought it did, maybe not. Will add eedback.
7. There's not much difference in the bump, it's not a proper rumble pad, but I will see what I can do now that block damage actually scales with swing.
8. What hud mode? it should work in hand or wrist mode.

**Comment by DoctorPCfin** [comment]
1. Indeed
2. The problem is more fundamental. I suppose being able to reach the fourth block would help _a little_ but some kind of a timber mod really would be a better option. The problem with Treecapitator is the fact that it increases the durability of the individual woodblock (to make the total chopping time be the same), which is fine on desktop, but really infuriating when it is you having to swing your arm for three dozen times.
3. Can't the server be modified, too? Perhaps splitting to "Vivecrat" and "Vivecraft lite" (that maintains all multiplayer compatibility) would be the way to go. You wouldn't be the first mod to do so.
4. That would probably work better, yes.
5. I had to make this short to fit into the list, what i really said was "I don't know the formula by which Swing translates into block famage multiplier"
6. It did, but doesn't anymore.
7. nice :)
8. The toolbar is always rendered on top of the tool you are using, no matter the hudmode. This feels... strange, when you are trying to take a look at your sword xD

**Comment by fucnknown** [comment]
2- If your problem is with Treecapitator, then don't use it. It's a mod issue/feature. I personally use Veinminer for a similar effect.  
3- Move around more, attack the beast and be ready to TP and move. It's not that hard

**Comment by jrbudda** [comment]
creeper radius tweaked in versions 3 and 30 for singleplayer. Also tweaked for multiplayer with latest VFE. need feedback on balance.
