### ISSUE TITLE
Detection direction messed up while moving

### ISSUE THREAD

**Issue by Nixill** [jrbudda/minecrift#197]
_Forge installation with no mods, singleplayer, creative_

When you're moving in free-movement and placing direction-based blocks (for example stairs, doors, pistons, floor signs), it will assume you're facing the direction you're moving instead of the direction you're facing or the direction relative to the block.

When you're not moving, the game assumes your direction of facing to be the direction from your head to the cursor, even if you're looking at a right angle to where you're pointing. (There is also another bug with this detection, see #198)

**Comment by Techjar** [comment]
This isn't a bug, it's just a result of how we handle free movement. While moving, your vanilla head orientation (not related to where you're physically looking) is determined by the left controller orientation, whereas normally determined by the direction from the vanilla eye position to the crosshair. We do this to avoid overriding a whole bunch of vanilla code that uses the head orientation, and for mod compatibility since some mods are dumb and re-implement the ray tracing.

**Comment by Nixill** [comment]
Your comment and closure is based on an older version of my issue that takes only moving behavior into account. I updated it to take standing behavior into account as well, which is not as you described. It felt silly to make that a separate issue.

**Comment by Techjar** [comment]
I explained the standing behavior. It's the direction from the vanilla eye position to the crosshair position, which matches as you described, so what's the issue?

**Comment by Nixill** [comment]
Oh.

Oh, I didn't read your comment closely enough. Sorry. #198 still seems like a bug though, but I did make that one separate. So I guess this one's rightly closed.
