### ISSUE TITLE
[Forge Mod] LOTR - cannot fast travel

### ISSUE THREAD

**Issue by royda** [jrbudda/minecrift#206]
Single-player, using 1.7.10 Vivecraft version 30 with Forge and the LOTR mod (http://lotrminecraftmod.wikia.com/wiki/Lord_of_the_Rings_Mod):
--I cannot fast travel.
I go to VR Settings, then controller buttons option, then set a button to "Menu" (which is a LOTR option which opens the map screen). This works. I can click the Vive controller button and open the map. However, once selecting a location that I can fast travel to, I cannot fast travel. There is no error, but nothing happens. Returning to the controller buttons menu and setting another controller button to "Fast Travel" and clicking with that button on the map location does nothing as well.

**Comment by jrbudda** [comment]
does clicking with the regular mouse work?

**Comment by royda** [comment]
Negative. Nor does hitting the LOTR-default key of "F."

Actually, it seems as if the keyboard might not be registering at all in menus. Example: in VR Settings, Controller Buttons section, if you pick a button to change and cycle through it and get to the option to use Keyboard Input and then click to enter the key binding, you will see two tick marks, ala:  '  '  which is clearly when you're supposed to hit a keyboard key. Hitting keyboard keys does nothing however. No key is ever entered in as Keyboard Input.

**Comment by jrbudda** [comment]
if you switch to 'seated' mode does WASD work? almost sounds like LOTR is doing something odd with the keyboard and mouse inputs.

**Comment by jrbudda** [comment]
how do you fast travel normally? im trying this mod in regular minecraft and F does nothing and clicking on the map does nothing.

**Comment by jrbudda** [comment]
Ok i figured it out. Yes it appears the 'Fast Travel' action doesn't work on the map (why on earth is that a keybind and not just a button on the map screen??). I cannot fix that on my end, they're listening directly for keyboard keys and not actions.

 But there's a couple options, because we've run into this before.

1) I had no problem binding 'keyboard:press f' to a controller button and using that to initiate fast travel.
2) I was able to both open the map and initiate fast travel by pulling up the steam keyboard via left_grip+left_appmenu and hitting L and F that way.
