### ISSUE TITLE
[Request] SLI support

### ISSUE THREAD

**Issue by woutwoot** [jrbudda/minecrift#252]
It would probably be very hard to add, but I'm going to ask anyway. 
Would it be possible to add support for SLI as to render each eye on another GPU?

**Comment by jrbudda** [comment]
Nope. Minecraft rendering is not compatible with SLI.

**Comment by woutwoot** [comment]
I figured it would probably not be possible/easy. Thanks for checking though :)

**Comment by Techjar** [comment]
It's probably *possible* to support, even using Java with LWJGL. If the rendering pipeline was written properly and we set an SLI profile, it might work. The problem is, it would require completely rewriting Minecraft's rendering from the ground up, because it's bad and broken in so many ways, and that just isn't going to happen.
