### ISSUE TITLE
[Wishlist] 3rd person view for display mirror.

### ISSUE THREAD

**Issue by jrbudda** [jrbudda/minecrift#95]
To investigate: Render world a 3rd time with 3rd person camera for presenting to display mirror

**Comment by Techjar** [comment]
This would be nice but it's going to really hurt performance because of Minecraft's shitty rendering code. We already have a hard enough time keeping the frame rate up when rendering everything twice. Let's just shelve it for 1.7.10, and look into it again whenever we update to a much newer MC version, because I think they've greatly improved the render performance.

**Comment by nightfiree** [comment]
Thanks for peeping the idea. 

I actually am going to try something out.  I wana try running Vivecraft, and then open a second instance of minecraft and run this mod http://mods.curse.com/bukkit-plugins/minecraft/spectate. Find myself in my game and spectate myself.  I geuss the real question is do bukkit mods even work w/ forge mods. Could this work w/ vivecraft even?

No idea how it will work....hate being at work and having to do stuff.  Will let you know if i can get it to work when i get home and test.

**Comment by Techjar** [comment]
If you use Thermos then bukkit plugins work, though its compatibility with Forge mods is somewhat dubious.

**Comment by nightfiree** [comment]
I have just been playing on single player w/ mods.  My minecraft understanding is a bit limited.  I tried standing up a local server w/ thermos but had no sucess. What a pain to have to download pluggins.  Trying to find a forge equivalent but cant. Also seems that what i want is in 1.8.0 w/ spectate mode.

**Comment by Techjar** [comment]
We'll try a mirror option to render a 3rd projection of the game (first or third person) in the eventual 1.10 port, since later versions of Minecraft bring along some significant performance boosts. I was doing some testing and the frame rates were significantly higher at the same render distance, so they definitely seem to have improved the world renderer.

**Comment by jrbudda** [comment]
I also think new MC's have that spectator mode, which means fuller support for changing the renderviewEntity. crossing my fingers we can hijack that and do it proper.

**Comment by Techjar** [comment]
Uh, are you sure about that? Spectator is just a gamemode which makes the player invisible and able to clip through blocks, I thought.

**Comment by jrbudda** [comment]
No I think there's a thing where you can be a zombie or spider or stuff. I
could be wrong.

**Comment by jrbudda** [comment]
closing, continue discussion in #104
