### ISSUE TITLE
[Wishlist] Custom Vivecraft server

### ISSUE THREAD

**Issue by jrbudda** [jrbudda/minecrift#97]
Need to pick a server disto: Vanilla, Forge, Spigot, Thermos... Idk what else there even is.
- Server should be aware of player head, hands, aiming positions/directions
- should support all forms of locomotion

**Comment by Techjar** [comment]
Honestly, Forge is the best option here, as we could just write a Forge mod/coremod to handle all of this. Don't bother with modifying the vanilla or bukkit-based servers, that's just going to be a mess.

**Comment by possi** [comment]
As I don't expect that you will choose Spigot, as it doesn't offer the ability forge can bring I would recommend to create a clean API for client/server communication, that also can be implemented by other server software.
I would like to do a spigot implementation, as I assume it can be done without modifying the server-source.

**Comment by fucnknown** [comment]
How updated are Forge servers for 1.7.10?  
I there any active development anymore?  

The reason I'm a proponent of Thermos, is not because of the spigot/Forge compatibility but because of it's numerous optimizations and fixes for Forge mods.

If you think that working with it can be a problem, like Techjar suggests, then a fork of Forge seems the most wise choice. I still push for forking the latest/most stable Thermos development.

My 2¢

**Comment by jrbudda** [comment]
closing. continue discussion in #110
